spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_list
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

